const PDFDocument = require("pdfkit");

function generateCarPDF(car, finance, res) {
  const doc = new PDFDocument({ margin: 50, size: "A4" });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="AutoMoX_${car.make}_${car.model}_Summary.pdf"`
  );
  doc.pipe(res);

  const PRIMARY = "#1a1a2e";
  const ACCENT  = "#e63946";
  const MUTED   = "#6b7280";
  const DIVIDER = "#e5e7eb";
  const PAGE_W  = doc.page.width - 100;

  doc.rect(0, 0, doc.page.width, 70).fill(PRIMARY);
  doc.fillColor("#ffffff").fontSize(24).font("Helvetica-Bold").text("AutoMoX", 50, 20);
  doc.fillColor("#cbd5e1").fontSize(10).font("Helvetica").text("Vehicle Summary & Financing Plan", 50, 48);

  const dateStr = new Date().toLocaleDateString("en-BD", {
    year: "numeric", month: "long", day: "numeric",
  });
  doc.fillColor("#94a3b8").fontSize(9).text(`Generated: ${dateStr}`, 0, 52, {
    align: "right", width: doc.page.width - 50,
  });

  doc.moveDown(3);

  function sectionTitle(label) {
    doc.moveDown(0.5);
    doc.fillColor(ACCENT).fontSize(10).font("Helvetica-Bold").text(label.toUpperCase());
    doc.moveTo(50, doc.y + 2).lineTo(50 + PAGE_W, doc.y + 2).strokeColor(DIVIDER).lineWidth(0.5).stroke();
    doc.moveDown(0.5);
  }

  function kvRow(key, value, highlight = false) {
    const y = doc.y;
    doc.fillColor(MUTED).fontSize(10).font("Helvetica").text(key, 50, y, { width: 200 });
    doc
      .fillColor(highlight ? ACCENT : PRIMARY)
      .fontSize(10)
      .font(highlight ? "Helvetica-Bold" : "Helvetica")
      .text(value, 260, y, { width: PAGE_W - 210, align: "right" });
    doc.moveDown(0.4);
  }

  const formatBDT = (n) => "BDT " + Math.round(n).toLocaleString("en-BD");
  const fmtShort  = (n) => Math.round(n).toLocaleString("en-BD");

  sectionTitle("Vehicle specifications");
  kvRow("Make",         car.make);
  kvRow("Model",        car.model);
  kvRow("Year",         String(car.year));
  kvRow("VIN",          car.vin || "N/A");
  kvRow("Fuel type",    car.fuelType);
  kvRow("Color",        car.color || "N/A");
  kvRow("Stock status", car.stockStatus);
  kvRow("Listed price", formatBDT(car.price), true);

  sectionTitle("Financing plan");
  kvRow("Listed price",        formatBDT(finance.carPrice));
  kvRow("Down payment",        formatBDT(finance.downPayment));
  kvRow("Loan amount",         formatBDT(finance.carPrice - finance.downPayment));
  kvRow("Annual interest rate",`${finance.interestRate}%`);
  kvRow("Loan term",           `${finance.loanTermMonths} months`);
  kvRow("Monthly installment", formatBDT(finance.monthlyPayment), true);
  kvRow("Total interest",      formatBDT(finance.totalInterest));
  kvRow("Total payable",       formatBDT(finance.totalPayable), true);

  sectionTitle("Amortization snapshot (first 3 months)");

  const monthlyRate = finance.interestRate / 100 / 12;
  let balance = finance.carPrice - finance.downPayment;
  const colX    = [50, 160, 280, 400, 510];
  const headers = ["Month", "Opening balance", "Interest", "Principal", "Closing balance"];

  doc.fillColor(PRIMARY).fontSize(9).font("Helvetica-Bold");
  headers.forEach((h, i) =>
    doc.text(h, colX[i], doc.y, { width: 110, align: i === 0 ? "left" : "right" })
  );
  doc.moveDown(0.3);
  doc.moveTo(50, doc.y).lineTo(50 + PAGE_W, doc.y).strokeColor(DIVIDER).lineWidth(0.5).stroke();
  doc.moveDown(0.3);

  for (let m = 1; m <= Math.min(3, finance.loanTermMonths); m++) {
    const interest  = balance * monthlyRate;
    const principal = finance.monthlyPayment - interest;
    const closing   = balance - principal;
    const y = doc.y;
    doc.fillColor(PRIMARY).fontSize(9).font("Helvetica");
    doc.text(String(m),           colX[0], y, { width: 100 });
    doc.text(fmtShort(balance),   colX[1], y, { width: 110, align: "right" });
    doc.text(fmtShort(interest),  colX[2], y, { width: 110, align: "right" });
    doc.text(fmtShort(principal), colX[3], y, { width: 100, align: "right" });
    doc.text(fmtShort(closing),   colX[4], y, { width: 100, align: "right" });
    doc.moveDown(0.4);
    balance = Math.max(0, closing);
  }

  doc.moveDown(3);
  doc.moveTo(50, doc.y).lineTo(50 + PAGE_W, doc.y).strokeColor(DIVIDER).lineWidth(0.5).stroke();
  doc.fillColor(MUTED).fontSize(8).text(
    "This document is an automated estimate generated by AutoMoX. " +
    "Financing terms are indicative and subject to lender approval.",
    50, doc.y + 8, { align: "center", width: PAGE_W }
  );

  doc.end();
}

module.exports = generateCarPDF;